name: habit_hero
description: A privacy-first habit tracker app built with Flutter.
version: 0.1.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_slidable: ^2.0.0
  flutter_colorpicker: ^1.0.3
  material_symbols_icons: ^4.2746.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
